### ISSUE TITLE
git push hangs

### ISSUE THREAD

**Issue by moiseevigor** [git-lfs/lfs-test-server#68]
Hi all! Have this issue, we work with Atlassian. Do I do something wrong?
Here is the trace

```
GIT_TRACE=1 GIT_CURL_VERBOSE=1 git push

18:45:22.972872 git.c:344               trace: built-in: git 'push'
18:45:22.973464 run-command.c:334       trace: run_command: 'ssh' 'git@bitbucket.org' 'git-receive-pack '\''groupp/repoo.git'\'''
18:45:24.445509 run-command.c:334       trace: run_command: '.git/hooks/pre-push' 'origin' 'git@bitbucket.org:groupp/repoo.git'
18:45:24.449638 git.c:561               trace: exec: 'git-lfs' 'pre-push' 'origin' 'git@bitbucket.org:groupp/repoo.git'
18:45:24.449724 run-command.c:334       trace: run_command: 'git-lfs' 'pre-push' 'origin' 'git@bitbucket.org:groupp/repoo.git'
18:45:24.459124 trace git-lfs: run_command: 'git' version
18:45:24.462023 trace git-lfs: run_command: 'git' config -l
18:45:24.465080 trace git-lfs: tq: running as batched queue, batch size of 100
18:45:26.073199 trace git-lfs: pre-push: refs/heads/master d3075da831a34d08da1f9883b95521d2fa28dd5f refs/heads/master 1aefc2592af566cbe0bd848e61ae70af68055b2c
18:45:26.073503 trace git-lfs: run_command: git rev-list --objects d3075da831a34d08da1f9883b95521d2fa28dd5f --not --remotes=origin --
18:45:26.076189 trace git-lfs: run_command: git cat-file --batch
18:45:26.081487 trace git-lfs: tq: sending batch of size 1
18:45:26.081777 trace git-lfs: api: batch 1 files
18:45:26.081831 trace git-lfs: creds: git credential fill ("http", "server-o:9999", "")
Username for 'http://server-o:9999': user
Password for 'http://user@server-o:9999': 
18:45:30.111265 trace git-lfs: Filled credentials for http://server-o:9999/
18:45:30.111530 trace git-lfs: HTTP: POST http://server-o:9999/objects/batch
> POST /objects/batch HTTP/1.1
> Host: server-o:9999
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Authorization: Basic * * * * *
> Content-Length: 123
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/2.3.2 (GitHub; linux amd64; go 1.8.1)
> 
{"operation":"upload","objects":[{"oid":"11f6bf651ae98a35d051d6ba7d0af90a239ce33891c787ff46b34da1906c37ec","size":307374}]}18:45:30.115886 trace git-lfs: HTTP: 200


< HTTP/1.1 200 OK
< Content-Length: 513
< Content-Type: application/vnd.git-lfs+json
< Date: Wed, 04 Oct 2017 16:44:57 GMT
< 
18:45:30.119045 trace git-lfs: HTTP: {"objects":[{"oid":"11f6bf651ae98a35d051d6ba7d0af90a239ce33891c787ff46b34da1906c37ec","size":307374,"actions":{"download":{"href":"http://server-o:9999/objects/11f6bf651ae98a35d051d6ba7d0af90a239ce33891c787ff46b34da1906c37ec","header":{"Accept":"application/vnd.git-lfs"},"expires_at":"0001-01-01T00:00:00Z"},"upload":{"href":"http://server-o:9999/objects/11f6bf651ae98a35d051d6ba7d0af90a239ce33891c787ff46b34da1906c37ec","header":{"Accept":"application/vnd.git-lfs"},"expires_at":"0001-01-01T00:00:00Z"}}}]}
{"objects":[{"oid":"11f6bf651ae98a35d051d6ba7d0af90a239ce33891c787ff46b34da1906c37ec","size":307374,"actions":{"download":{"href":"http://server-o:9999/objects/11f6bf651ae98a35d051d6ba7d0af90a239ce33891c787ff46b34da1906c37ec","header":{"Accept":"application/vnd.git-lfs"},"expires_at":"0001-01-01T00:00:00Z"},"upload":{"href":"http://server-o:9999/objects/11f6bf651ae98a35d051d6ba7d0af90a239ce33891c787ff46b34da1906c37ec","header":{"Accept":"application/vnd.git-lfs"},"expires_at":"0001-01-01T00:00:00Z"}}}]}18:45:30.119211 trace git-lfs: tq: starting transfer adapter "basic"
Git LFS: (0 of 1 files) 0 B / 300.17 KB                                                                                                                                        18:45:30.119472 trace git-lfs: creds: git credential fill ("http", "server-o:9999", "")
Git LFS: (0 of 1 files) 0 B / 300.17 KB                                                                                                                                        ^C
Exiting because of "interrupt" signal.
18:45:46.913179 trace git-lfs: tq: retrying object 11f6bf651ae98a35d051d6ba7d0af90a239ce33891c787ff46b34da1906c37ec: LFS: Git credentials for http://server-o:9999/ not found:
'git credential fill' error: signal: interrupt
```

log del server

```
2017-10-04T16:44:57Z aea0cdd6c40e lfs[191] [server.go:341]: method=POST url=/objects/batch status=200 request_id=b2cc7035-47ec-268d-7c4b-b904b9aa50d9
```

![screenshot from 2017-10-04 18-49-42](https://user-images.githubusercontent.com/993491/31188329-d4720614-a934-11e7-84eb-33cc1dde3841.png)

But when I click on `http://server-o:9999/mgmt/raw/11f6bf651ae98a35d051d6ba7d0af90a239ce33891c787ff46b34da1906c37ec` it returns `Not Found`

**Comment by technoweenie** [comment]
Do you have a [git credential helper](https://help.github.com/articles/caching-your-github-password-in-git/) installed? It looks like it's hanging because it's prompting you for another password.

The batch request prompted you for a password:

```
18:45:26.081831 trace git-lfs: creds: git credential fill ("http", "server-o:9999", "")
Username for 'http://server-o:9999': user
Password for 'http://user@server-o:9999': 
18:45:30.111265 trace git-lfs: Filled credentials for http://server-o:9999/
18:45:30.111530 trace git-lfs: HTTP: POST http://server-o:9999/objects/batch
```

That request works fine. However, it seems to prompt again while attempting to upload the file:

```
Git LFS: (0 of 1 files) 0 B / 300.17 KB                                                                                                                                        18:45:30.119472 trace git-lfs: creds: git credential fill ("http", "server-o:9999", "")
Git LFS: (0 of 1 files) 0 B / 300.17 KB                                                                                                                                        ^C
Exiting because of "interrupt" signal.
18:45:46.913179 trace git-lfs: tq: retrying object 11f6bf651ae98a35d051d6ba7d0af90a239ce33891c787ff46b34da1906c37ec: LFS: Git credentials for http://server-o:9999/ not found:
```

Setting up a credential helper should fix this.

That said, there are some things that could be checked in the client:

1. Why isn't the LFS credential cacher working? It should've saved the password for the `objects/batch` request.
2. Why isn't it prompting for creds on upload/download requests in the transfer queue? Prompting for each file would be really annoying, so it may be better to disable the prompt in the transfer queue and just bail early.

**Comment by moiseevigor** [comment]
Thank you very much! Yes I had `git credentials` installed, I've cached credentials with

```
git config --global credential.helper cache
```
And now `git push` works like a charm!

Sorry for bothering, but I've tested deleting and it works fine on the git level, but I still see files in `LFS_CONTENTPATH` that have equal size of the originals. I've deleted files with 

```
git rm test-lfs/*
git push
``` 

And on bitbucket I see everything clean

```
 test-lfs/file.pkl DELETED
  Comment   More
-version https://git-lfs.github.com/spec/v1
-oid sha256:11f6bf651ae98a35d051d6ba7d0af90a239ce33891c787ff46b34da1906c37ec
-size 307374
```
Maybe I lack some knowledge on how the GIT-LFS works?

**Comment by technoweenie** [comment]
Hey FWIW, I discovered that LFS isn't caching http credentials internally. https://github.com/git-lfs/git-lfs/pull/2648 fixes that, and will be released with v2.3.3. So even if you don't have a credential cacher set up, you'll only have to enter your creds at most once per `git lfs` command.

> Sorry for bothering, but I've tested deleting and it works fine on the git level, but I still see files in `LFS_CONTENTPATH` that have equal size of the originals.

Are you running `lfs-test-server` in the same directory as your repository? Do you see something like this in your `git status`?

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	lfs-content/
	lfs.db
```

`lfs-test-server` is only for LFS testing. I wouldn't use it to store real data. Why aren't you using bitbucket as your lfs host?

**Comment by moiseevigor** [comment]
I was not completely clear about the setup, it is a bit more sophisticated, the lfs-test-server runs in the docker container on the other physical host, so it is not influenced by the current git repo. Yes we evaluated the bitbucket's lfs, but it quite unfeasible for us to move so much bits of data on our dialup, even with 100mbit/s :) 

We are not much concerned about the risk of data loss, we have numerous backups, but we need a fast data rotation that is only possibile in LAN.

The second reason is I actually liked the idea behind LFS and really optimistic about lfs-test-server and would like to help with testing and bug hunting to bring it on the production level!

So back to the problem, as far as I see on files delete the lfs-test-server does not receive any request on `git push`, that sounds like a main reason to me. Maybe the hook did worked properly? What do you think?

**Comment by technoweenie** [comment]
> The second reason is I actually liked the idea behind LFS and really optimistic about lfs-test-server and would like to help with testing and bug hunting to bring it on the production level!

Unfortunately, I have no time to commit to this (even just reviewing PRs). My recommendation would be to fork it.

> So back to the problem, as far as I see on file delete the lfs-test-server does not receive any request on git push, that sounds like a main reason to me. Maybe the hook did worked properly? What do you think?

LFS doesn't really have a way to delete files, as it's modeled after Git. With Git, you don't actually _delete_ files unless a branch is deleted or force pushed, and all references to that file are gone. Even then, it's up to the Git remote to purge them on the server.

There is a proposal for LFS object expirations: https://github.com/git-lfs/git-lfs/issues/2623. Basically, deleting the LFS objects on the server, even though that LFS pointer still exists in the Git repository somewhere. This would be used for things like rolling backups.

**Comment by moiseevigor** [comment]
Clear. Thank you for your time and the support!! I'm closing this issue.
